### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by DRECKINTERNET** [frozen2077/wled-joy-HA#1]
it doesnt work correct

it creates a new entity with none behind it and deosnt do anything

**Comment by cmd204** [comment]
Slight update. It turns out the light has to be online when you start up this integration. I turned the light on and then the integration found it. It looks like the integration added it to itself, which is a little odd because WLED already "owned" the light. Even with this additional functionality, there was no color temperature selector added to the light: 

![image](https://github.com/frozen2077/wled-joy-HA/assets/93741382/8e4ae1c2-2582-4aee-a24d-1023193d8ca6)

**Comment by frozen2077** [comment]
Fixed some lines in light.py, should be working now.

**Comment by frozen2077** [comment]
> Slight update. It turns out the light has to be online when you start up this integration. I turned the light on and then the integration found it. It looks like the integration added it to itself, which is a little odd because WLED already "owned" the light. Even with this additional functionality, there was no color temperature selector added to the light:
> 
> ![image](https://private-user-images.githubusercontent.com/93741382/328612230-8e4ae1c2-2582-4aee-a24d-1023193d8ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDM2MDUsIm5iZiI6MTcxNTEwMzMwNSwicGF0aCI6Ii85Mzc0MTM4Mi8zMjg2MTIyMzAtOGU0YWUxYzItMjU4Mi00YWVlLWEyNGQtMTAyMzE5M2Q4Y2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNWQxNGQyMmQ5Njg5NjE2MzE3OTMxZDFjNTU3ODA0OTEzYWVhMzViODY3MDFlZWRjMTI3Y2NjY2JjNjNiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcGRsjuiYly8dp2jQCRrOPUuTnCp9uZYjHPFybrfaNE)
Fixed some lines in light.py, should be working now.
To work properly:
1. Lights should be deleted in the official component first
2. Lights could only be added by auto-discovery(Bug, might fix later)

**Comment by frozen2077** [comment]
> To work properly:
> 
> 1. Lights should be deleted in the official component first
> 2. Lights could only be added by auto-discovery(Bug, might fix later)
> 3. Restart HA after modifying any files in the component



> Agreed @DRECKINTERNET . I decided to add this as a custom repo in HACS and then add the integration in HA. Adding the rep and downloading in HACS works fine. After HA restarted, the integration is found, but then when I try to add it I get prompted to put information into a field. There's nothing telling me what I should add. See screenshot below.
> 
> Tagging @frozen2077 (repo creator) in case they are aware of what to do here.
> 
> ![image](https://private-user-images.githubusercontent.com/93741382/328610161-177b9c46-272d-4cb7-90f3-f6e5f59b0b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDQwMTgsIm5iZiI6MTcxNTEwMzcxOCwicGF0aCI6Ii85Mzc0MTM4Mi8zMjg2MTAxNjEtMTc3YjljNDYtMjcyZC00Y2I3LTkwZjMtZjZlNWY1OWIwYjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3NDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYWM1YjkzZjVjNTc5MGE0NzI5ZTE5Yjk5Y2IxZTA2MjA0YjA1YWQzNDljNGJkNzg4NzUzMmQ4YjFhNjhiY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jCuXlbw-m2nS6wAocJSGyev23IAnyItVkKSJoDjXjJ8)

Fixed some lines in light.py, should be working now.
To work properly:
Lights should be deleted in the official component first
Lights could only be added by auto-discovery(Bug, might fix later)
Restart HA after modifying any files in the component

**Comment by frozen2077** [comment]
> it doesnt work correct
> 
> it creates a new entity with none behind it and deosnt do anything


Fixed some lines in light.py, should be working now.
To work properly:

Lights should be deleted in the official component first
Lights could only be added by auto-discovery(Bug, might fix later)
Restart HA after modifying any files in the component
