### ISSUE TITLE
not working Color Temp issues

### ISSUE THREAD

**Issue by DjBac** [frozen2077/wled-joy-HA#2]
First of all, finally a wled integration with color tempt control. The problem is that I cannot choose any effects.

**Comment by frozen2077** [comment]
> First of all, finally a wled integration with color tempt control. The problem is that I cannot choose any effects.

Do you have ant presets? I replaced default effects list with preset list.

**Comment by DjBac** [comment]
No Presets on this light, just tried to create one and it works!! Thank you!
