### ISSUE TITLE
No joy with latest update

### ISSUE THREAD

**Issue by SdeGeata** [frozen2077/wled-joy-HA#3]
Hello;

   I recently updated my Home Assistant os and core to the latest versions, but since then WLED Joy doesn't work. I tried a reinstall and it throws an error 'unknown' at config. Any chance of a compatible update soon?

Core: 2024.10.4
Supervisor: 2024.10.3
Operating System: 13.2
Frontend: 20241002.4 ⸱ legacy

**Comment by pilonull** [comment]
well, I manually installed the integration by copying "wled_joy" folder to my custom_components folder, I restarted home assistant, and can see the integration is available... HOWEVER, it never auto-detects my wled I'm trying to add. The light is turned on and connected to the network, and it has a preset set on it.

**Comment by frozen2077** [comment]
Updated to be compatible with Core 12.5 (Wled v0.20.2)
